### ISSUE TITLE
Invalid argument in backend/Makefile

### ISSUE THREAD

**Issue by killroy42** [doitintl/banias#9]
There are a few occurrences of `--GCSSchemasBucketName=(SCHEMAS_BUCKET)` in the Makefile, which cause errors. I presume it is meant to read `--GCSSchemasBucketName=$(SCHEMAS_BUCKET)`.

Is the current Makefile working for you with this error?

**Comment by yorambenyaacov** [comment]
You are right :-)

Fixed in commit 3458872f6af90af3ce149e1638160b1e1d80f7e4
[Bug fix with SCHEMAS_BUCKET param](https://github.com/doitintl/banias/commit/3458872f6af90af3ce149e1638160b1e1d80f7e4)
